#!/usr/bin/env bash
# Clone qemu-minimal tooling + batesste-ansible, install the batesste collection,
# then run gen-vm WITH Ansible provisioning to build the guest qcow (rocm-xio @
# nvme-kv + kmod + GRUB cheats). Cached in /data/images; skip unless FORCE=1.
set -Eeuo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$HERE/common.sh"
TOOLING=/opt/qemu-minimal
ANSIBLE_SRC=/opt/batesste-ansible
# gen-vm boots a throwaway builder VM via ${QEMU_PATH}qemu-system-x86_64 (a string
# PREFIX, default empty => PATH lookup). Our QEMU is built at /opt/qemu/build, not on
# PATH, so we must pass QEMU_PATH (dir + trailing slash) into gen-vm too.
: "${QEMU_BIN:=/opt/qemu/build/qemu-system-x86_64}"
# gen-vm writes the final image to ${IMAGES}/${VM_NAME}.qcow2 (see gen-vm tail:
# create_image_with_backing / NO_BACKING mv). Verified against the real gen-vm.
QCOW="$IMAGES_DIR/$VM_NAME.qcow2"

vm_build() {
  # STAGE is read by common.sh's die()/log() via ${STAGE:-error}; shellcheck
  # cannot follow that cross-function read.
  # shellcheck disable=SC2034
  local STAGE=build-vm
  if [ -f "$QCOW" ] && [ "${FORCE:-0}" != "1" ]; then
    log build-vm "qcow exists ($QCOW); skip (FORCE=1 to rebuild)"; return 0
  fi
  # --- tooling repo (gen-vm + launcher) ---
  if [ ! -d "$TOOLING/.git" ]; then
    log build-vm "cloning tooling $QEMU_MINIMAL_REMOTE@$QEMU_MINIMAL_BRANCH"
    GIT_TERMINAL_PROMPT=0 git clone --branch "$QEMU_MINIMAL_BRANCH" "$QEMU_MINIMAL_REMOTE" "$TOOLING" \
      || die "tooling clone failed (private? see README 'Private fork clone')"
  fi
  [ -f "$TOOLING/$GENVM_SCRIPT" ] || die "GENVM_SCRIPT $GENVM_SCRIPT not in tooling repo"
  # --- ansible provisioning repo (the batesste collection) ---
  if [ ! -d "$ANSIBLE_SRC/.git" ]; then
    log build-vm "cloning ansible $ANSIBLE_REMOTE@$ANSIBLE_BRANCH"
    GIT_TERMINAL_PROMPT=0 git clone --branch "$ANSIBLE_BRANCH" "$ANSIBLE_REMOTE" "$ANSIBLE_SRC" \
      || die "ansible clone failed"
  fi
  [ -f "$ANSIBLE_SRC/$ANSIBLE_PLAYBOOK" ]  || die "playbook $ANSIBLE_PLAYBOOK missing in ansible repo"
  [ -f "$ANSIBLE_SRC/$ANSIBLE_INVENTORY" ] || die "inventory $ANSIBLE_INVENTORY missing in ansible repo"
  # gen-vm hard-requires $ANSIBLE_DIR/requirements.yml (prepare_ansible_setup)
  # and installs sbates130272.batesste from it. Fail early with a clear message.
  [ -f "$ANSIBLE_SRC/requirements.yml" ] || die "requirements.yml missing in ansible repo (gen-vm requires it)"
  # Install the batesste collection itself so FQCN role lookups resolve, plus deps.
  log build-vm "installing batesste collection + requirements"
  ansible-galaxy collection install "$ANSIBLE_SRC" --force >>"$LOG_DIR/gen-vm.log" 2>&1 \
    || die "batesste collection install failed (see $LOG_DIR/gen-vm.log)"
  ansible-galaxy collection install -r "$ANSIBLE_SRC/requirements.yml" >>"$LOG_DIR/gen-vm.log" 2>&1 || true
  # gen-vm expects ansible.cfg AT $ANSIBLE_DIR (it cd's there + sets ANSIBLE_CONFIG).
  # The repo keeps it under playbooks/; synthesize a root cfg if absent.
  #
  # remote_tmp is forced under /tmp on purpose. gen-vm's cloud-config adds a 9p
  # "mounts:" entry for /home/${USER}/code that runs in cc_mounts BEFORE the user
  # is created; "mount -a" then makes /home/ubuntu (and .../code) as root, so the
  # later "useradd -m" leaves /home/ubuntu owned by root:root. Ansible's default
  # remote_tmp (~/.ansible/tmp) is created by the connection plugin as the
  # non-root login user and fails ("Failed to create temporary directory" ->
  # UNREACHABLE). A /tmp-rooted remote_tmp sidesteps that; the wrapper playbook
  # below then repairs the home ownership before the real provisioning runs.
  if [ ! -f "$ANSIBLE_SRC/ansible.cfg" ]; then
    cat >"$ANSIBLE_SRC/ansible.cfg" <<EOF
[defaults]
roles_path = $ANSIBLE_SRC/roles
collections_path = $HOME/.ansible/collections
host_key_checking = False
remote_tmp = /tmp/.ansible-tmp
EOF
  fi
  # gen-vm runs a single fixed playbook ($ANSIBLE_PLAYBOOK). It corrupts nothing
  # upstream to drop our own wrapper playbook alongside it (same pattern as the
  # synthesized ansible.cfg above) that (1) fixes the root-owned /home/${USER}
  # left behind by the 9p mount race, then (2) imports the real guest playbook
  # unchanged. Point gen-vm at this wrapper instead of the bare playbook.
  local wrap_pb="playbooks/rocm-xio-kv-guest-wrapped.yml"
  cat >"$ANSIBLE_SRC/$wrap_pb" <<EOF
---
# Auto-generated by docker/rocm-xio-kv-ceph build-vm. Repairs the home dir that
# gen-vm's 9p "mounts:" cloud-config leaves owned by root, then runs the real
# guest provisioning playbook. Do not edit; regenerated on every build.
- name: Repair guest home ownership (9p mount race workaround)
  hosts: "{{ targets | default('rocm_xio_kv') }}"
  gather_facts: false
  become: true
  tasks:
    - name: Ensure {{ ansible_user }} owns its home directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: true

- ansible.builtin.import_playbook: $(basename "$ANSIBLE_PLAYBOOK")
EOF
  ANSIBLE_PLAYBOOK="$wrap_pb"
  # gen-vm hard-requires SSH_KEY_FILE (the PUBLIC key; default $HOME/.ssh/id_ed25519.pub)
  # and exits if absent. It also SSHes into the guest with the default identity (no -i),
  # so the matching private key must sit at the default $HOME/.ssh/id_ed25519. Generate an
  # ed25519 keypair if the public key is missing; never overwrite an existing key.
  local sshkey="${SSH_KEY_FILE:-$HOME/.ssh/id_ed25519.pub}"
  if [ ! -f "$sshkey" ]; then
    mkdir -p "$HOME/.ssh"; chmod 700 "$HOME/.ssh"
    ssh-keygen -t ed25519 -N '' -f "$HOME/.ssh/id_ed25519" -q
    sshkey="$HOME/.ssh/id_ed25519.pub"
    log build-vm "generated ephemeral SSH keypair for guest provisioning"
  fi
  # The host ~/.ssh is bind-mounted read-only at $HOME/.ssh, so it also drags in
  # the host's ~/.ssh/config. OpenSSH refuses any config/key not owned by the
  # current (in-container root) user and ABORTS the connection with
  # "Bad owner or permissions on .../config" (exit 255). gen-vm's wait_for_ssh and
  # ansible both use the default identity/config, so every SSH probe silently fails
  # for the full 600s timeout -> "VM did not accept SSH within 600 seconds!".
  #
  # ssh resolves ~/.ssh/config via the passwd home dir (getpwuid), not $HOME, so
  # exporting HOME alone is NOT enough. Stage a clean, root-owned ~/.ssh (keys only,
  # no config) and repoint root's passwd home at it so every ssh gen-vm/ansible
  # spawns reads the clean config. .ansible is symlinked back so the batesste
  # collection installed earlier under the original HOME stays visible. The original
  # HOME/.ssh (the mounted host keys) is left untouched; this only runs in the
  # throwaway build-vm container.
  local genvm_home="$RUN_DIR/genvm-home"
  rm -rf "$genvm_home"; mkdir -p "$genvm_home/.ssh"; chmod 700 "$genvm_home/.ssh"
  cp "$sshkey" "$genvm_home/.ssh/"
  local privkey="${sshkey%.pub}"
  [ -f "$privkey" ] && { cp "$privkey" "$genvm_home/.ssh/"; chmod 600 "$genvm_home/.ssh/$(basename "$privkey")"; }
  [ -d "$HOME/.ansible" ] && ln -sfn "$HOME/.ansible" "$genvm_home/.ansible"
  local genvm_sshkey
  genvm_sshkey="$genvm_home/.ssh/$(basename "$sshkey")"
  # Repoint root's passwd home dir so OpenSSH stops reading the mounted host config.
  if [ -w /etc/passwd ]; then
    sed -i "s#^\(root:[^:]*:[^:]*:[^:]*:[^:]*\):[^:]*:#\1:${genvm_home}:#" /etc/passwd
  else
    log build-vm "WARN: /etc/passwd not writable; ssh may abort on mounted ~/.ssh/config"
  fi
  # --- run gen-vm WITH provisioning ---
  log build-vm "running $GENVM_SCRIPT with Ansible (playbook=$ANSIBLE_PLAYBOOK)"
  ( cd "$TOOLING/$(dirname "$GENVM_SCRIPT")" && \
    HOME="$genvm_home" \
    VM_NAME="$VM_NAME" RELEASE=noble VCPUS="$VCPUS" VMEM="$VMEM" \
    SSH_KEY_FILE="$genvm_sshkey" \
    QEMU_PATH="$(dirname "$QEMU_BIN")/" \
    SSH_PORT="$SSH_PORT" IMAGES="$IMAGES_DIR" \
    ANSIBLE_SETUP=true ANSIBLE_DIR="$ANSIBLE_SRC" \
    ANSIBLE_PLAYBOOK="$ANSIBLE_PLAYBOOK" ANSIBLE_INVENTORY="$ANSIBLE_INVENTORY" \
      "./$(basename "$GENVM_SCRIPT")" >>"$LOG_DIR/gen-vm.log" 2>&1 ) \
    || die "gen-vm failed (see $LOG_DIR/gen-vm.log)"
  [ -f "$QCOW" ] || die "gen-vm did not produce $QCOW (check IMAGES/VM_NAME in gen-vm.log)"
  log build-vm "qcow ready: $QCOW"
}
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then vm_build; fi
