#!/bin/bash
# Copyright (c) Advanced Micro Devices, Inc. All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Write random LBAs via xio-tester nvme-ep, then read each
# back with dd and verify the data matches the expected LFSR
# pattern.
#
# The LFSR seed controls both the data pattern and the LBA
# sequence (via getRandomLba in nvme-ep.hip).
#
# The expected data pattern is generated by xio-tester
# --dump-pattern, which calls the same C++ dataPattern()
# function used by the GPU kernel.  The random LBA sequence
# is replayed in Python (getRandomLba only).

set -e

NVME_DEVICE=""
LFSR_SEED="${LFSR_SEED:-0x1234}"
BASE_LBA="${BASE_LBA:-0}"
NUM_WRITES="${NUM_WRITES:-64}"
MEMORY_MODE="${MEMORY_MODE:-0}"
QUEUE_LENGTH="${QUEUE_LENGTH:-128}"
BATCH_SIZE="${BATCH_SIZE:-}"
NUM_QUEUES="${NUM_QUEUES:-}"

XIO_TESTER="${XIO_TESTER:-./build/xio-tester}"
TEMP_DIR="${TEMP_DIR:-/tmp/nvme-ep-rw-verify}"

resolve_nvme_paths() {
    local device="$1"
    local real
    real="$(readlink -f "$device")" || return 1
    local node
    node="$(basename "$real")"

    if [[ "$node" =~ ^nvme[0-9]+n[0-9]+$ ]]; then
        local controller
        controller="$(basename "$(readlink -f \
            "/sys/class/block/$node/device")")" || return 1
        NVME_CONTROLLER="/dev/$controller"
        NVME_NAMESPACE="$device"
    else
        NVME_CONTROLLER="$real"
        NVME_NAMESPACE="${device}n1"
    fi
}

if [ $# -lt 1 ]; then
    echo "Usage: $0 <nvme-controller>"
    echo ""
    echo "Environment variables:"
    echo "  LFSR_SEED     Seed for pattern + LBA sequence"
    echo "  BASE_LBA      Starting LBA (default: 0)"
    echo "  NUM_WRITES    Number of writes (default: 64)"
    echo "  MEMORY_MODE   Memory mode (default: 0)"
    echo "  XIO_TESTER    Path to xio-tester binary"
    exit 1
fi

NVME_DEVICE="$1"
shift

while [[ $# -gt 0 ]]; do
    case $1 in
        --seed|-s) LFSR_SEED="$2"; shift 2 ;;
        --base-lba|-b) BASE_LBA="$2"; shift 2 ;;
        --num-writes|-n) NUM_WRITES="$2"; shift 2 ;;
        --help|-h)
            echo "Usage: $0 <nvme-controller>"
            echo "Options:"
            echo "  --seed, -s        LFSR seed"
            echo "  --base-lba, -b    Starting LBA"
            echo "  --num-writes, -n  Number of writes"
            exit 0 ;;
        *) echo "Error: Unknown option $1"
           exit 1 ;;
    esac
done

if [ "$EUID" -ne 0 ]; then
    echo "Error: requires root"
    exit 1
fi

if [ ! -e "$NVME_DEVICE" ]; then
    echo "Error: $NVME_DEVICE not found"
    exit 1
fi

if [ ! -f "$XIO_TESTER" ]; then
    echo "Error: xio-tester not found at $XIO_TESTER"
    exit 1
fi

if ! command -v python3 &>/dev/null; then
    echo "Error: python3 not found"
    exit 1
fi

NVME_CONTROLLER=""
NVME_NAMESPACE=""
if ! resolve_nvme_paths "$NVME_DEVICE"; then
    echo "Error: failed to resolve NVMe paths for $NVME_DEVICE"
    exit 1
fi

NS="$NVME_NAMESPACE"
if [ ! -e "$NS" ]; then
    echo "Error: namespace $NS not found"
    exit 1
fi

mkdir -p "$TEMP_DIR"

LBA_SIZE=$(blockdev --getss "$NS")
NS_BYTES=$(blockdev --getsize64 "$NS")
NS_CAPACITY=$((NS_BYTES / LBA_SIZE))

echo "========================================"
echo "Random write-verify test"
echo "========================================"
echo "Controller:    $NVME_CONTROLLER"
echo "Namespace:     $NS"
echo "LFSR seed:     $LFSR_SEED"
echo "Base LBA:      $BASE_LBA"
echo "Num writes:    $NUM_WRITES"
echo "Memory mode:   $MEMORY_MODE"
echo "Batch size:    ${BATCH_SIZE:-1 (default)}"
echo "Num queues:    ${NUM_QUEUES:-1 (default)}"
echo "LBA size:      $LBA_SIZE bytes"
echo "NS capacity:   $NS_CAPACITY LBAs"
echo ""

echo "Step 1: Writing $NUM_WRITES random LBAs..."
write_cmd="$XIO_TESTER nvme-ep"
write_cmd="$write_cmd --write-io ${NUM_WRITES}"
write_cmd="$write_cmd --controller $NVME_CONTROLLER"
write_cmd="$write_cmd --access-pattern random"
write_cmd="$write_cmd --lbas-per-io 1"
write_cmd="$write_cmd --lfsr-seed $LFSR_SEED"
write_cmd="$write_cmd --base-lba $BASE_LBA"
write_cmd="$write_cmd --queue-length $QUEUE_LENGTH"
write_cmd="$write_cmd -m $MEMORY_MODE"
if [ -n "$BATCH_SIZE" ]; then
    write_cmd="$write_cmd --batch-size $BATCH_SIZE"
fi
if [ -n "$NUM_QUEUES" ]; then
    write_cmd="$write_cmd --num-queues $NUM_QUEUES"
fi
if [ -n "${ROCXIO_NVME_QUEUE_ID:-}" ]; then
    write_cmd="$write_cmd --queue-id $ROCXIO_NVME_QUEUE_ID"
fi

echo "Command: $write_cmd"
WRITE_LOG="$TEMP_DIR/write.log"
if ! $write_cmd > "$WRITE_LOG" 2>&1; then
    echo "Write FAILED - xio-tester output:"
    cat "$WRITE_LOG"
    exit 1
fi

echo "Write completed"
echo ""

echo "Step 2: Generating expected patterns..."
BATCH="${BATCH_SIZE:-1}"
PATTERN_SIZE=$((BATCH * LBA_SIZE))
EXPECTED_BUF="$TEMP_DIR/expected_buf.bin"
$XIO_TESTER --dump-pattern "$EXPECTED_BUF" \
    --dump-pattern-seed "$LFSR_SEED" \
    --dump-pattern-size "$PATTERN_SIZE" \
    --dump-pattern-block-size "$LBA_SIZE" \
    --dump-pattern-offset 0 2>/dev/null

# Quiesce before namespace readback in Step 3.
sleep 5

echo "Step 3: Computing LBAs and verifying..."

python3 << PYEOF
import sys

lfsr_seed_str = '${LFSR_SEED}'
if lfsr_seed_str.startswith('0x') or \
   lfsr_seed_str.startswith('0X'):
    lfsr_seed = int(lfsr_seed_str, 16)
else:
    lfsr_seed = int(lfsr_seed_str)

num_writes = ${NUM_WRITES}
base_lba = ${BASE_LBA}
lba_size = ${LBA_SIZE}
ns_capacity = ${NS_CAPACITY}
ns_dev = '${NS}'
batch_size = ${BATCH}
buf_file = '${EXPECTED_BUF}'


def get_random_lba(op_index, cmd_id,
                   lfsr_seed, base_lba,
                   lba_range):
    """Reproduces getRandomLba() from nvme-ep.hip."""
    M64 = 0xFFFFFFFFFFFFFFFF
    M32 = 0xFFFFFFFF
    seed = (op_index * 0x9e3779b9
            + ((cmd_id * 0x85ebca6b) & M32)
            + lfsr_seed) & M64
    seed = (seed ^ (seed >> 16)) & M64
    seed = (seed * 0xc2b2ae35) & M64
    seed = (seed ^ (seed >> 13)) & M64
    seed = (seed * 0x9e3779b9) & M64
    seed = (seed ^ (seed >> 16)) & M64
    return base_lba + (seed % lba_range)


with open(buf_file, 'rb') as f:
    full_buf = f.read()

patterns = {}
for b in range(batch_size):
    off = b * lba_size
    patterns[b] = full_buf[off:off + lba_size]
    print(f"Expected pattern slot {b}"
          f" ({len(patterns[b])} bytes):"
          f" first 8 = {patterns[b][:8].hex()}")

lba_to_slot = {}
for i in range(num_writes):
    cmd_id = (i % 65535) + 1
    lba = get_random_lba(
        i, cmd_id, lfsr_seed, base_lba, ns_capacity)
    lba_to_slot[lba] = i % batch_size

unique_lbas = sorted(lba_to_slot.keys())
print(f"Unique LBAs written: {len(unique_lbas)}"
      f" (from {num_writes} ops)")

fail_count = 0
ok_count = 0

with open(ns_dev, 'rb') as dev:
    for lba in unique_lbas:
        slot = lba_to_slot[lba]
        expected = patterns[slot]
        dev.seek(lba * lba_size)
        actual = dev.read(lba_size)

        if actual != expected:
            print(f"FAIL: LBA {lba} mismatch"
                  f" (got {len(actual)} bytes,"
                  f" first 8 = {actual[:8].hex()})")
            fail_count += 1
            if fail_count <= 3:
                for j in range(min(len(actual),
                                   len(expected))):
                    if actual[j] != expected[j]:
                        print(
                            f"  first diff at byte"
                            f" {j}:"
                            f" got 0x{actual[j]:02x}"
                            f" expected"
                            f" 0x{expected[j]:02x}")
                        break
        else:
            ok_count += 1

print(f"Results: {ok_count} OK, {fail_count} FAIL"
      f" / {len(unique_lbas)} LBAs")

if fail_count == 0:
    print("All LBAs verified OK")
    sys.exit(0)
else:
    print("Data verification FAILED")
    sys.exit(1)
PYEOF
